### ISSUE TITLE
Bug of numbers in the hyperlink

### ISSUE THREAD

**Issue by Davidyzy** [zzj0402/Logico#35]
https://en.wikipedia.org/wiki/Wikipedia
numbers in hyperlink has wrong color
![number error](https://user-images.githubusercontent.com/32407699/34319540-b5ddbc14-e81f-11e7-9098-a2f30ba0fb89.png)

**Comment by zzj0402** [comment]
Turn <x> and <num> tags into black might solve the coloring problem. Spacing bug should be fixed now. The number tagged as verbs shown above seems strange. I am not able to replicate the situation in 0.0.6 version. Please update to the latest version of the extension.
